name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install dgl>=0.7.0 -f https://data.dgl.ai/wheels/repo.html
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: academic_graph.settings.test
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        python manage.py test --noinput
